---
name: Self
on: [push, pull_request]

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: self
      - run: magick test.png test.gif
