---
name: Lint
on: [push, pull_request]

jobs:
  lint:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run lint
